name: Build packages
on:
  release:
    types: [released, prereleased]

jobs:
  deploy:
    environment: pypi
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools
    - name: Build
      run: |
        python -m build
    - name: Upload package
      uses: pypa/gh-action-pypi-publish@master
